# =====================================================================
#  _config.yml  ·  Minimal Mistakes + GitHub Pages · Kevin Kukla
# =====================================================================

#######################################################################
# 1 · Global site metadata
#######################################################################
title:        "Kevin J. Kukla, PhD · Portfolio"
description:  "Instructional Design · Technical Writing · eLearning"

# Where GitHub Pages will publish the site.
# ‣ If this repo is *kjkportfolio*, keep baseurl exactly as below.
# ‣ If you later move everything into  <username>.github.io, change
#   baseurl to "" (empty string).
url:      "https://kjkukla.github.io"   # GitHub Pages root (never slash-ending)
baseurl:  "/kjkportfolio"               # repo name *with* leading slash

#######################################################################
# 2 · Theme settings
#######################################################################
remote_theme: "mmistakes/minimal-mistakes"   # official upstream theme
minimal_mistakes_skin: "dirt"                # built-in color palette

# Enable the JavaScript skin switcher (adds light/dark toggle in nav bar)
# skin_switcher: true                        # ← optional

#######################################################################
# 3 · GitHub-Pages–allowed plugins
#######################################################################
plugins:
  - jekyll-feed
  - jekyll-include-cache

#######################################################################
# 4 · Collections  (one Markdown file per project)
#######################################################################
collections:
  projects:
    output:    true                 # each item gets its own page
    permalink: /projects/:path/     # pretty URLs

# Default front-matter for everything inside the `projects` collection
defaults:
  - scope:
      path: ""                      # match every file
      type: projects
    values:
      layout: single                # full-width page
      author_profile: false

#######################################################################
# 5 · Navigation links that appear in the top bar
#######################################################################
header_pages:
  - about.md
  - projects/index.md

#######################################################################
# 6 · Build options (safe defaults — rarely need edits)
#######################################################################
markdown: kramdown
highlighter: rouge
permalink: pretty
# Incremental build speeds local `jekyll serve` but is ignored by GitHub
incremental: true

########################################################################
# 7 Social icons
########################################################################
footer:
  links:
    - label: LinkedIn
      icon: "fab fa-linkedin"
      url:  "https://linkedin.com/in/kevin-kukla"
    - label: Email
      icon: "fas fa-envelope"
      url:  "mailto:kevin@example.com"

#######################################################################
# End
#######################################################################
 
