# ================================================================
#  _config.yml  ·  Minimal Mistakes + GitHub Pages · Kevin Kukla
# ================================================================

# --- Site metadata ------------------------------------------------
title: "Kevin Kukla · Portfolio"
description: "Instructional Design · Technical Writing · eLearning"

# ↓↓↓ Step 1: tell Jekyll where the site will live on GitHub Pages
url: "https://kjkukla.github.io"   # always your GitHub Pages root
baseurl: "/kjkportfolio"           # repo name *with* leading slash
                                    # (leave empty "" in a personal-site repo)

# --- Theme and plugins -------------------------------------------
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-include-cache
#---Skin color-----------------------------------------------------

minimal_mistakes_skin: "dirt"    # or "aqua", "contrast", "dark", "dirt",
                                # "mint", "neon", "plum", "sunrise"

# Optional social icons (Font Awesome names)
social:
  - platform: linkedin
    url: "https://linkedin.com/in/kevin-kukla"
  - platform: github
    url: "https://github.com/kjkukla"


# --- Custom collections ------------------------------------------
collections:
  projects:
    output: true                  # each item gets its own page
    permalink: /projects/:path/   # pretty URLs

defaults:
  - scope:
      path: ""                    # applies to every file in the repo
      type: projects
    values:
      layout: single              # clean one-column layout
      author_profile: false

# --- Navigation ---------------------------------------------------
header_pages:
  - about.md
  - projects/index.md
