title: "Kevin Kukla · Portfolio"
description: "Instructional Design · Technical Writing · eLearning"

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-include-cache   # ← add this
